spring:
  application:
    name: careerpilot-ai

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: careerpilot

  flyway:
    enabled: true
    default-schema: careerpilot
    schemas: careerpilot

security:
  jwt:
    secret: ${JWT_SECRET:Q2FyZWVyUGlsb3RBdXRoU2VjcmV0S2V5Rm9yRGV2RW52aXJvbm1lbnQxMjM0NTY3ODkwMTIzNDU2Nzg5MA==}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}